[package]
name = "rust_lib_pwdgenf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
migration = { path = "./migration" }

anyhow = "1.0.104"
chacha20 = "0.10.2"
chrono = "0.4.45"
cipher = "0.5.2"
flutter_rust_bridge = "=2.13.0"
sea-orm = { version = "2.0.2", features = [
    "sqlx-sqlite",
    "runtime-tokio",
    "macros",
] }
sha2 = "0.11.0"
time = { version = "0.3.55", features = ["formatting", "macros"] }
tokio = { version = "1.53.1", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "fmt",
    "time",
] }
thiserror = "2.0.20"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
