// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../clean_error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `uniformly_pick`

Future<void> validate({required Request request}) =>
    RustLib.instance.api.crateApiCalculatePasswordValidate(request: request);

Future<String> calculatePassword({required Request request}) => RustLib
    .instance
    .api
    .crateApiCalculatePasswordCalculatePassword(request: request);

class Request {
  final String userName;
  final String platform;
  final int nonceOffset;
  final bool useUpLetter;
  final bool useLowLetter;
  final bool useNumber;
  final bool useSpChar;
  final int pwdLen;
  final String mainPassword;

  const Request({
    required this.userName,
    required this.platform,
    required this.nonceOffset,
    required this.useUpLetter,
    required this.useLowLetter,
    required this.useNumber,
    required this.useSpChar,
    required this.pwdLen,
    required this.mainPassword,
  });

  @override
  int get hashCode =>
      userName.hashCode ^
      platform.hashCode ^
      nonceOffset.hashCode ^
      useUpLetter.hashCode ^
      useLowLetter.hashCode ^
      useNumber.hashCode ^
      useSpChar.hashCode ^
      pwdLen.hashCode ^
      mainPassword.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Request &&
          runtimeType == other.runtimeType &&
          userName == other.userName &&
          platform == other.platform &&
          nonceOffset == other.nonceOffset &&
          useUpLetter == other.useUpLetter &&
          useLowLetter == other.useLowLetter &&
          useNumber == other.useNumber &&
          useSpChar == other.useSpChar &&
          pwdLen == other.pwdLen &&
          mainPassword == other.mainPassword;
}
