// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../clean_error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> validate({required CreateAcctDataRequest request}) =>
    RustLib.instance.api.crateApiCreateAcctDataValidate(request: request);

Future<void> createAcctData({
  required String appSupportDirectory,
  required CreateAcctDataRequest request,
}) => RustLib.instance.api.crateApiCreateAcctDataCreateAcctData(
  appSupportDirectory: appSupportDirectory,
  request: request,
);

class CreateAcctDataRequest {
  final String userName;
  final String platform;
  final String remark;
  final int nonceOffset;
  final bool useUpLetter;
  final bool useLowLetter;
  final bool useNumber;
  final bool useSpChar;
  final int pwdLen;

  const CreateAcctDataRequest({
    required this.userName,
    required this.platform,
    required this.remark,
    required this.nonceOffset,
    required this.useUpLetter,
    required this.useLowLetter,
    required this.useNumber,
    required this.useSpChar,
    required this.pwdLen,
  });

  @override
  int get hashCode =>
      userName.hashCode ^
      platform.hashCode ^
      remark.hashCode ^
      nonceOffset.hashCode ^
      useUpLetter.hashCode ^
      useLowLetter.hashCode ^
      useNumber.hashCode ^
      useSpChar.hashCode ^
      pwdLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateAcctDataRequest &&
          runtimeType == other.runtimeType &&
          userName == other.userName &&
          platform == other.platform &&
          remark == other.remark &&
          nonceOffset == other.nonceOffset &&
          useUpLetter == other.useUpLetter &&
          useLowLetter == other.useLowLetter &&
          useNumber == other.useNumber &&
          useSpChar == other.useSpChar &&
          pwdLen == other.pwdLen;
}
