// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../clean_error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from_query_result_nullable`, `from_query_result`, `select_cols_nested`

Future<ReadAllAcctDataResult> readAllAcctData({
  required String appSupportDirectory,
  required String searchTerm,
  required BigInt pageIndex,
  required BigInt pageSize,
}) => RustLib.instance.api.crateApiReadAllAcctDataReadAllAcctData(
  appSupportDirectory: appSupportDirectory,
  searchTerm: searchTerm,
  pageIndex: pageIndex,
  pageSize: pageSize,
);

class AcctDataPartialModel {
  final int id;
  final String userName;
  final String platform;

  const AcctDataPartialModel({
    required this.id,
    required this.userName,
    required this.platform,
  });

  @override
  int get hashCode => id.hashCode ^ userName.hashCode ^ platform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcctDataPartialModel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userName == other.userName &&
          platform == other.platform;
}

class ReadAllAcctDataResult {
  final BigInt totalCount;
  final List<AcctDataPartialModel> pageContent;

  const ReadAllAcctDataResult({
    required this.totalCount,
    required this.pageContent,
  });

  @override
  int get hashCode => totalCount.hashCode ^ pageContent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadAllAcctDataResult &&
          runtimeType == other.runtimeType &&
          totalCount == other.totalCount &&
          pageContent == other.pageContent;
}
