// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../clean_error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from_query_result_nullable`, `from_query_result`, `select_cols_nested`

Future<ReadAcctDataResult> readAcctData({
  required String appSupportDirectory,
  required int id,
}) => RustLib.instance.api.crateApiReadAcctDataReadAcctData(
  appSupportDirectory: appSupportDirectory,
  id: id,
);

class ReadAcctDataResult {
  final int id;
  final String userName;
  final String platform;
  final String remark;
  final int nonceOffset;
  final bool useUpLetter;
  final bool useLowLetter;
  final bool useNumber;
  final bool useSpChar;
  final int pwdLen;
  final String updatedAt;

  const ReadAcctDataResult({
    required this.id,
    required this.userName,
    required this.platform,
    required this.remark,
    required this.nonceOffset,
    required this.useUpLetter,
    required this.useLowLetter,
    required this.useNumber,
    required this.useSpChar,
    required this.pwdLen,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userName.hashCode ^
      platform.hashCode ^
      remark.hashCode ^
      nonceOffset.hashCode ^
      useUpLetter.hashCode ^
      useLowLetter.hashCode ^
      useNumber.hashCode ^
      useSpChar.hashCode ^
      pwdLen.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadAcctDataResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userName == other.userName &&
          platform == other.platform &&
          remark == other.remark &&
          nonceOffset == other.nonceOffset &&
          useUpLetter == other.useUpLetter &&
          useLowLetter == other.useLowLetter &&
          useNumber == other.useNumber &&
          useSpChar == other.useSpChar &&
          pwdLen == other.pwdLen &&
          updatedAt == other.updatedAt;
}
